# Generated by Django 5.1.2 on 2024-11-11 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_univerhistorycard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlovhasi')),
                ('photo', models.ImageField(upload_to='media/photo/', verbose_name='rasm')),
            ],
            options={
                'verbose_name': 'Markazlar',
                'verbose_name_plural': 'Markazlar',
            },
        ),
        migrations.CreateModel(
            name='FilialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlovhasi')),
                ('body', models.TextField(verbose_name='texti')),
                ('photo', models.ImageField(upload_to='media/photo/', verbose_name='rasm')),
            ],
            options={
                'verbose_name': 'Filial Tarixi',
                'verbose_name_plural': 'Filial Tarixi',
            },
        ),
        migrations.CreateModel(
            name='KengashCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlovhasi')),
                ('photo', models.ImageField(upload_to='media/photo/', verbose_name='rasm')),
            ],
            options={
                'verbose_name': 'Kengash Kategory',
                'verbose_name_plural': 'Kengash Kategory',
            },
        ),
        migrations.CreateModel(
            name='Raxbaryat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Sarlovhasi')),
                ('position', models.CharField(max_length=250, verbose_name='Lavozimi')),
                ('number', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('photo', models.ImageField(upload_to='media/photo/', verbose_name='rasm')),
            ],
            options={
                'verbose_name': 'Raxbaryat hodmlari',
                'verbose_name_plural': 'Kengash Article',
            },
        ),
        migrations.AlterModelOptions(
            name='univerhistorycard',
            options={'verbose_name': 'Universitet Tarixi', 'verbose_name_plural': 'Universitet Tarixi'},
        ),
        migrations.CreateModel(
            name='CenterArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Sarlovhasi')),
                ('position', models.CharField(max_length=250, verbose_name='Lavozimi')),
                ('number', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('photo', models.ImageField(upload_to='media/photo/', verbose_name='rasm')),
                ('body', models.TextField(verbose_name='Markaz Malumotlari')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_kengash', to='myapp.categorycenter')),
            ],
            options={
                'verbose_name': 'Markaz Malumotlari',
                'verbose_name_plural': 'Markaz Malumotlari',
            },
        ),
        migrations.CreateModel(
            name='Centerplus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Sarlovhasi')),
                ('position', models.CharField(max_length=250, verbose_name='Lavozimi')),
                ('photo', models.ImageField(upload_to='media/photo/', verbose_name='rasm')),
                ('tg', models.CharField(max_length=100, verbose_name='telegram')),
                ('tell', models.CharField(max_length=100, verbose_name='tell:')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('insta', models.CharField(max_length=100, verbose_name='Instagram')),
                ('facebook', models.CharField(max_length=100, verbose_name='Facebook')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.centerarticle')),
            ],
            options={
                'verbose_name': 'Markaz Malumotlari',
                'verbose_name_plural': 'Markaz Malumotlari',
            },
        ),
        migrations.CreateModel(
            name='KengashArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlovhasi')),
                ('photo', models.ImageField(upload_to='media/photo/', verbose_name='rasm')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_kengash', to='myapp.kengashcategory')),
            ],
            options={
                'verbose_name': 'Kengash Article',
                'verbose_name_plural': 'Kengash Article',
            },
        ),
    ]
